//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.22 at 12:52:21 AM CST 
//


package com.quiputech.sms.providers.infobip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="authentification" type="{}authentificationType"/>
 *         &lt;element name="message" type="{}messageType"/>
 *         &lt;element name="recipients" type="{}recipientsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authentification",
    "message",
    "recipients"
})
@XmlRootElement(name = "SMS")
public class SMS {

    @XmlElement(required = true)
    protected AuthentificationType authentification;
    @XmlElement(required = true)
    protected MessageType message;
    @XmlElement(required = true)
    protected RecipientsType recipients;

    /**
     * Gets the value of the authentification property.
     * 
     * @return
     *     possible object is
     *     {@link AuthentificationType }
     *     
     */
    public AuthentificationType getAuthentification() {
        return authentification;
    }

    /**
     * Sets the value of the authentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthentificationType }
     *     
     */
    public void setAuthentification(AuthentificationType value) {
        this.authentification = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link MessageType }
     *     
     */
    public MessageType getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageType }
     *     
     */
    public void setMessage(MessageType value) {
        this.message = value;
    }

    /**
     * Gets the value of the recipients property.
     * 
     * @return
     *     possible object is
     *     {@link RecipientsType }
     *     
     */
    public RecipientsType getRecipients() {
        return recipients;
    }

    /**
     * Sets the value of the recipients property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipientsType }
     *     
     */
    public void setRecipients(RecipientsType value) {
        this.recipients = value;
    }

}
